// Package models provides data structures for the workshop API.
package models

import (
	"fmt"
)

// MetricType represents a sensor metric type
type MetricType string

const (
	MetricTempCelsius     MetricType = "temp_celsius"
	MetricHumidityPercent MetricType = "humidity_percent"
	MetricCO2PPM          MetricType = "co2_ppm"
	MetricVoltage         MetricType = "voltage"
	MetricCurrent         MetricType = "current"
	MetricPower           MetricType = "power"
	MetricEnergy          MetricType = "energy"
)

// SensorConfigType represents the type of sensor configuration
type SensorConfigType string

const (
	SensorConfigEnvironment SensorConfigType = "environment"
	SensorConfigPower       SensorConfigType = "power"
)

// BuildingConfig represents a building in the YAML configuration
// ID is now autogenerated - do not specify in config
type BuildingConfig struct {
	Name        string       `yaml:"name"`
	Description string       `yaml:"description"`
	Address     string       `yaml:"address"`
	Rooms       []RoomConfig `yaml:"rooms"`
}

// RoomConfig represents a room in the YAML configuration
// ID is now autogenerated - do not specify in config
type RoomConfig struct {
	Name     string         `yaml:"name"`
	Type     string         `yaml:"type"`
	Floor    int            `yaml:"floor"`
	Capacity int            `yaml:"capacity"`
	Sensors  []SensorConfig `yaml:"sensors"`
}

// SensorConfig represents a sensor in the YAML configuration
// ID is now autogenerated - do not specify in config
// Each sensor config creates exactly one runtime sensor with fused metrics
type SensorConfig struct {
	Name        string           `yaml:"name"`
	Type        SensorConfigType `yaml:"type"`
	Description string           `yaml:"description"`
}

// DataConfig represents the complete YAML configuration structure
type DataConfig struct {
	Buildings []BuildingConfig `yaml:"buildings"`
}

// ConvertToBuilding converts BuildingConfig to runtime Building model
func (bc *BuildingConfig) ConvertToBuilding(id int) Building {
	return Building{
		ID:          id,
		Name:        bc.Name,
		Description: bc.Description,
		Address:     bc.Address,
	}
}

// ConvertToRoom converts RoomConfig to runtime Room model
func (rc *RoomConfig) ConvertToRoom(buildingID int, roomID int) Room {
	return Room{
		ID:         roomID,
		BuildingID: buildingID,
		Name:       rc.Name,
		Type:       rc.Type,
		Floor:      rc.Floor,
		Capacity:   rc.Capacity,
	}
}

// ConvertToSensor converts SensorConfig to runtime Sensor model.
// Each config entry creates exactly one sensor with fused metrics.
// Environment sensors return temperature/humidity/CO2 in a single reading.
// Power sensors return voltage/current/power/energy in a single reading.
func (sc *SensorConfig) ConvertToSensor(roomID int, sensorID int) (*Sensor, error) {
	switch sc.Type {
	case SensorConfigEnvironment:
		return &Sensor{
			ID:          sensorID,
			RoomID:      roomID,
			Name:        sc.Name,
			Type:        SensorEnvironment,
			Description: sc.Description,
		}, nil
	case SensorConfigPower:
		return &Sensor{
			ID:          sensorID,
			RoomID:      roomID,
			Name:        sc.Name,
			Type:        SensorPower,
			Description: sc.Description,
		}, nil
	default:
		return nil, fmt.Errorf("unknown sensor type: %s (must be 'environment' or 'power')", sc.Type)
	}
}

// Validate validates the configuration structure
func (dc *DataConfig) Validate() error {
	if len(dc.Buildings) == 0 {
		return fmt.Errorf("no buildings defined in configuration")
	}

	for i, b := range dc.Buildings {
		if b.Name == "" {
			return fmt.Errorf("building at index %d has no name", i)
		}

		for j, r := range b.Rooms {
			if r.Name == "" {
				return fmt.Errorf("room in building '%s' at index %d has no name", b.Name, j)
			}
			if r.Type == "" {
				return fmt.Errorf("room '%s' in building '%s' has no type", r.Name, b.Name)
			}

			for k, s := range r.Sensors {
				if s.Name == "" {
					return fmt.Errorf("sensor in room '%s' at index %d has no name", r.Name, k)
				}
				if s.Type != SensorConfigEnvironment && s.Type != SensorConfigPower {
					return fmt.Errorf("sensor '%s' in room '%s' has invalid type: %s (must be 'environment' or 'power')", s.Name, r.Name, s.Type)
				}
			}
		}
	}

	return nil
}
