// Package generators provides mock data generation for the workshop API.
package generators

import (
	"fmt"
	"sync"

	"github.com/zabbix-workshop/nlld/internal/models"
	"github.com/zabbix-workshop/nlld/pkg/config"
)

var (
	// buildings contains the static building/location data
	buildings []models.Building

	// rooms contains all rooms across buildings
	rooms []models.Room

	// sensors contains all sensor definitions
	sensors []models.Sensor

	// ID counters for autogeneration (persistent per config load)
	nextBuildingID int = 10
	nextRoomID     int = 100
	nextSensorID   int = 1000
	idMu           sync.Mutex

	// dataLoaded ensures we only load data once
	dataLoaded bool
	dataMu     sync.Mutex
)

func init() {
	loadDataFromConfig()
}

// loadDataFromConfig loads building, room, and sensor data from YAML configuration
func loadDataFromConfig() {
	dataMu.Lock()
	defer dataMu.Unlock()

	if dataLoaded {
		return
	}

	cfg, err := config.LoadDataConfig()
	if err != nil {
		panic(fmt.Sprintf("Failed to load data configuration: %v", err))
	}

	buildings = make([]models.Building, 0, len(cfg.Buildings))
	rooms = make([]models.Room, 0)
	sensors = make([]models.Sensor, 0)

	// Reset ID counters for fresh load
	idMu.Lock()
	nextBuildingID = 10
	nextRoomID = 100
	nextSensorID = 1000
	idMu.Unlock()

	for i := range cfg.Buildings {
		bc := &cfg.Buildings[i]

		// Get next building ID
		idMu.Lock()
		buildingID := nextBuildingID
		nextBuildingID++
		idMu.Unlock()

		// Convert building with autogenerated ID
		building := bc.ConvertToBuilding(buildingID)
		buildings = append(buildings, building)

		// Convert rooms and sensors for this building
		for j := range bc.Rooms {
			rc := &bc.Rooms[j]

			// Get next room ID
			idMu.Lock()
			roomID := nextRoomID
			nextRoomID++
			idMu.Unlock()

			// Convert room with autogenerated ID and parent building ID
			room := rc.ConvertToRoom(buildingID, roomID)

			// Convert sensors for this room (each config creates one sensor now)
			for k := range rc.Sensors {
				sc := &rc.Sensors[k]

				// Get next sensor ID
				idMu.Lock()
				sensorID := nextSensorID
				nextSensorID++
				idMu.Unlock()

				// Convert sensor with autogenerated ID
				sensor, err := sc.ConvertToSensor(roomID, sensorID)
				if err != nil {
					panic(fmt.Sprintf("Failed to convert sensor '%s' in room '%s': %v", sc.Name, rc.Name, err))
				}
				sensors = append(sensors, *sensor)

				// Add sensor ID to room's sensor list
				room.Sensors = append(room.Sensors, sensorID)
			}

			// Append the completed room (with sensors populated)
			rooms = append(rooms, room)
		}
	}

	dataLoaded = true
	fmt.Printf("Loaded configuration: %d buildings (IDs 10-%d), %d rooms (IDs 100-%d), %d sensors (IDs 1000-%d)\n",
		len(buildings), nextBuildingID-1, len(rooms), nextRoomID-1, len(sensors), nextSensorID-1)
}

// GetBuildings returns all buildings
func GetBuildings() []models.Building {
	return buildings
}

// GetBuildingByID returns a building by ID or nil if not found
func GetBuildingByID(id int) *models.Building {
	for i := range buildings {
		if buildings[i].ID == id {
			return &buildings[i]
		}
	}
	return nil
}

// GetRoomsByBuilding returns all rooms in a building
func GetRoomsByBuilding(buildingID int) []models.Room {
	var result []models.Room
	for i := range rooms {
		if rooms[i].BuildingID == buildingID {
			result = append(result, rooms[i])
		}
	}
	return result
}

// GetRoomByID returns a room by ID or nil if not found
func GetRoomByID(id int) *models.Room {
	for i := range rooms {
		if rooms[i].ID == id {
			return &rooms[i]
		}
	}
	return nil
}

// GetSensorsByRoom returns all sensors in a room
func GetSensorsByRoom(roomID int) []models.Sensor {
	var result []models.Sensor
	for i := range sensors {
		if sensors[i].RoomID == roomID {
			result = append(result, sensors[i])
		}
	}
	return result
}

// GetSensorByID returns a sensor by ID or nil if not found
func GetSensorByID(id int) *models.Sensor {
	for i := range sensors {
		if sensors[i].ID == id {
			return &sensors[i]
		}
	}
	return nil
}
